# Generated by Django 2.2.4 on 2019-09-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190903_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.SlugField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
